config_s3_bucket: 'sailboat-config'
environments:
  production:
    regions:
      - 'us-west-2'
project_name: 'sailboat'
services:
  app:
    command: './bin/start'
    ports:
      - '3000:3000'
    regions:
      us-west-2:
        repository_url: '583390024382.dkr.ecr.us-west-2.amazonaws.com/rails-app'
    resources:
      cpu_units: 256
      memory_units: 256
  worker:
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    regions:
      us-west-2:
        repository_url: '583390024382.dkr.ecr.us-west-2.amazonaws.com/rails-app'
    resources:
      cpu_units: 256
      memory_units: 256
  cable:
    command: 'bundle exec puma --bind tcp://0.0.0.0:28080 cable/config.ru'
    ports:
      - '28080:28080'
    regions:
      us-west-2:
        repository_url: '583390024382.dkr.ecr.us-west-2.amazonaws.com/rails-app'
    resources:
      cpu_units: 256
      memory_units: 256
